apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  alert.rules: |
    groups:
    - name: example
      rules:
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[1m]) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage"

